import turtle
#花瓣
for i in range(0,13):
    turtle.begin_fill()
    turtle.color("black")
    turtle.fillcolor("red")
    turtle.circle(60-5*i,120)
    turtle.forward (60-3*i)
    turtle.end_fill()
    turtle.right(18)
#花茎
turtle.penup()
turtle.goto(-40,-5)
turtle.pendown()
turtle.seth(-90)
turtle.width (10)
turtle.color("green")
turtle.forward(200)
#上面的叶子
turtle.penup()
turtle.goto(-40,-100)
turtle.pendown()
turtle.begin_fill()
turtle.width (2)
turtle.fillcolor("green")
turtle.seth(-10)
turtle.circle(60,120)
turtle.left(60)
turtle.circle(60,120)
turtle.end_fill()
#下面的叶子
turtle.penup()
turtle.goto(-45,-130)
turtle.pendown()
turtle.begin_fill()
turtle.width (2)
turtle.fillcolor("green")
turtle.right(90)
turtle.circle(-60,120)
turtle.right(60)
turtle.circle(-60,120)
turtle.end_fill()
